# Generated by Django 5.1.6 on 2025-03-03 04:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projectplan',
            options={},
        ),
        migrations.RemoveField(
            model_name='projectanswer',
            name='ai_feedback',
        ),
        migrations.RemoveField(
            model_name='projectanswer',
            name='question',
        ),
        migrations.RemoveField(
            model_name='projectplan',
            name='application',
        ),
        migrations.RemoveField(
            model_name='projectplan',
            name='business_plan_file',
        ),
        migrations.RemoveField(
            model_name='projectplan',
            name='expected_outcome',
        ),
        migrations.RemoveField(
            model_name='projectplan',
            name='implementation_period',
        ),
        migrations.RemoveField(
            model_name='projectplan',
            name='implementation_system',
        ),
        migrations.RemoveField(
            model_name='projectplan',
            name='innovation_point',
        ),
        migrations.RemoveField(
            model_name='projectplan',
            name='investment_amount',
        ),
        migrations.RemoveField(
            model_name='projectplan',
            name='market_research',
        ),
        migrations.RemoveField(
            model_name='projectplan',
            name='name',
        ),
        migrations.RemoveField(
            model_name='projectplan',
            name='summary',
        ),
        migrations.AddField(
            model_name='projectanswer',
            name='question_number',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='projectplan',
            name='last_answered_question',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='projectplan',
            name='status',
            field=models.CharField(choices=[('draft', '作成中'), ('phase1_complete', '基本質問完了'), ('phase2_in_progress', 'AI質問対応中'), ('completed', '完了')], default='draft', max_length=20),
        ),
        migrations.AddField(
            model_name='projectplan',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='projectanswer',
            name='answer',
            field=models.TextField(),
        ),
    ]
