# Generated by Django 5.1.6 on 2025-03-03 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_projectplan_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectplan',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
