# Generated by Django 5.1.6 on 2025-02-22 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subsidy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subsidy_id', models.CharField(max_length=100, unique=True)),
                ('title', models.CharField(max_length=500)),
                ('name', models.CharField(max_length=100)),
                ('subsidy_max_limit', models.BigIntegerField(null=True)),
                ('subsidy_rate', models.CharField(max_length=100)),
                ('target_area_search', models.CharField(max_length=100)),
                ('acceptance_start_datetime', models.DateTimeField(null=True)),
                ('acceptance_end_datetime', models.DateTimeField(null=True)),
                ('target_number_of_employees', models.CharField(max_length=100)),
                ('detail', models.TextField()),
                ('acceptance_status', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['acceptance_status'], name='api_subsidy_accepta_ea3949_idx'), models.Index(fields=['title'], name='api_subsidy_title_b8bb8f_idx')],
            },
        ),
    ]
