# Generated by Django 5.1.6 on 2025-03-03 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_projectplan_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectplan',
            name='phase1_locked',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='projectplan',
            name='status',
            field=models.CharField(choices=[('draft', '作成中'), ('phase1_complete', '基本質問完了'), ('phase2_in_progress', 'AI質問対応中'), ('phase2_complete', 'AI質問完了'), ('completed', '事業計画書完成')], default='draft', max_length=20),
        ),
    ]
