# Generated by Django 5.1.6 on 2025-02-23 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_delete_subsidy_remove_todo_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subsidy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('name', models.CharField(max_length=100)),
                ('subsidy_max_limit', models.IntegerField(blank=True, null=True)),
                ('subsidy_rate', models.CharField(blank=True, max_length=100, null=True)),
                ('target_area_search', models.CharField(blank=True, max_length=200, null=True)),
                ('acceptance_start_datetime', models.DateTimeField(blank=True, null=True)),
                ('acceptance_end_datetime', models.DateTimeField(blank=True, null=True)),
                ('target_number_of_employees', models.CharField(blank=True, max_length=100, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(default='1', max_length=10)),
            ],
        ),
    ]
