# Generated by Django 5.1.6 on 2025-02-23 07:53

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_subsidy'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subsidy',
            old_name='created_date',
            new_name='created_at',
        ),
        migrations.RemoveField(
            model_name='subsidy',
            name='status',
        ),
        migrations.AddField(
            model_name='subsidy',
            name='acceptance_status',
            field=models.CharField(default='1', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subsidy',
            name='detail',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subsidy',
            name='subsidy_id',
            field=models.CharField(default='temp_id', max_length=100, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subsidy',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='todo',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='subsidy',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='subsidy',
            name='subsidy_max_limit',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='subsidy',
            name='target_area_search',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddIndex(
            model_name='subsidy',
            index=models.Index(fields=['acceptance_status'], name='api_subsidy_accepta_ea3949_idx'),
        ),
        migrations.AddIndex(
            model_name='subsidy',
            index=models.Index(fields=['title'], name='api_subsidy_title_b8bb8f_idx'),
        ),
    ]
