# Generated by Django 5.1.6 on 2025-02-23 09:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_rename_created_date_subsidy_created_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=200)),
                ('representative', models.CharField(max_length=100)),
                ('established_date', models.DateField()),
                ('capital_amount', models.BigIntegerField()),
                ('employee_count', models.IntegerField()),
                ('industry_type', models.CharField(max_length=100)),
                ('postal_code', models.CharField(max_length=8)),
                ('address', models.CharField(max_length=200)),
                ('phone_number', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SubsidyEligibilityCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_title', models.CharField(max_length=200)),
                ('project_type', models.CharField(max_length=100)),
                ('investment_amount', models.BigIntegerField()),
                ('is_innovation', models.BooleanField(default=False)),
                ('is_digital', models.BooleanField(default=False)),
                ('has_sustainability', models.BooleanField(default=False)),
                ('is_eligible', models.BooleanField(null=True)),
                ('max_subsidy_amount', models.BigIntegerField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.companyprofile')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BusinessPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=20)),
                ('content', models.JSONField()),
                ('ai_feedback', models.JSONField(null=True)),
                ('is_premium', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('eligibility_check', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.subsidyeligibilitycheck')),
            ],
        ),
    ]
