# Generated by Django 5.1.6 on 2025-02-24 05:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_remove_subsidyeligibilitycheck_company_profile_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companyprofile',
            name='capital_amount',
        ),
        migrations.RemoveField(
            model_name='companyprofile',
            name='employee_count',
        ),
        migrations.RemoveField(
            model_name='companyprofile',
            name='industry_type',
        ),
        migrations.RemoveField(
            model_name='subsidyapplication',
            name='has_premium_support',
        ),
        migrations.RemoveField(
            model_name='subsidyapplication',
            name='total_budget',
        ),
        migrations.AddField(
            model_name='subsidyapplication',
            name='business_type',
            field=models.CharField(default='individual', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subsidyapplication',
            name='capital_amount',
            field=models.BigIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subsidyapplication',
            name='employee_count',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subsidyapplication',
            name='industry_type',
            field=models.CharField(default='service', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subsidyapplication',
            name='investment_amount',
            field=models.BigIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='company_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='phone_number',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='subsidyapplication',
            name='eligibility_check',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.subsidyeligibilitycheck'),
        ),
    ]
