# Generated by Django 5.1.6 on 2025-02-24 06:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_remove_companyprofile_capital_amount_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('draft', '下書き'), ('in_progress', '作成中'), ('submitted', '申請済み'), ('approved', '承認済み'), ('rejected', '却下')], default='draft', max_length=20)),
                ('company_info_completed', models.BooleanField(default=False)),
                ('basic_info_completed', models.BooleanField(default=False)),
                ('business_plan_completed', models.BooleanField(default=False)),
                ('documents_completed', models.BooleanField(default=False)),
                ('last_edited_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.subsidyapplication')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '申請進捗',
                'verbose_name_plural': '申請進捗',
            },
        ),
    ]
