# Generated by Django 5.1.6 on 2025-02-24 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_create_initial_questions'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='companyprofile',
            options={'verbose_name': '企業プロフィール', 'verbose_name_plural': '企業プロフィール'},
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='address',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='住所'),
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='company_name',
            field=models.CharField(max_length=100, verbose_name='会社名'),
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='established_date',
            field=models.DateField(blank=True, null=True, verbose_name='設立日'),
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='phone_number',
            field=models.CharField(max_length=15, verbose_name='電話番号'),
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='postal_code',
            field=models.CharField(blank=True, max_length=8, null=True, verbose_name='郵便番号'),
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='representative',
            field=models.CharField(max_length=100, verbose_name='代表者名'),
        ),
    ]
