# Generated by Django 5.1.6 on 2025-02-26 02:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_alter_projectplan_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projectanswer',
            options={'verbose_name': '事業計画回答', 'verbose_name_plural': '事業計画回答一覧'},
        ),
        migrations.AlterModelOptions(
            name='projectquestion',
            options={'ordering': ['order'], 'verbose_name': '事業計画質問', 'verbose_name_plural': '事業計画質問一覧'},
        ),
        migrations.AlterUniqueTogether(
            name='projectanswer',
            unique_together={('project', 'question')},
        ),
        migrations.RemoveField(
            model_name='projectquestion',
            name='ai_prompt',
        ),
        migrations.RemoveField(
            model_name='projectquestion',
            name='condition',
        ),
        migrations.RemoveField(
            model_name='projectquestion',
            name='dependent_on',
        ),
        migrations.RemoveField(
            model_name='projectquestion',
            name='options',
        ),
        migrations.RemoveField(
            model_name='projectquestion',
            name='question_id',
        ),
        migrations.RemoveField(
            model_name='projectquestion',
            name='question_type',
        ),
        migrations.RemoveField(
            model_name='projectquestion',
            name='required',
        ),
        migrations.AddField(
            model_name='projectquestion',
            name='is_required',
            field=models.BooleanField(default=True, verbose_name='必須'),
        ),
        migrations.AddField(
            model_name='projectquestion',
            name='placeholder',
            field=models.CharField(blank=True, max_length=200, verbose_name='プレースホルダー'),
        ),
        migrations.AddField(
            model_name='projectquestion',
            name='type',
            field=models.CharField(default='text', max_length=50, verbose_name='入力タイプ'),
        ),
        migrations.AlterField(
            model_name='projectanswer',
            name='answer',
            field=models.TextField(verbose_name='回答'),
        ),
        migrations.AlterField(
            model_name='projectanswer',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='api.projectplan'),
        ),
        migrations.AlterField(
            model_name='projectquestion',
            name='order',
            field=models.IntegerField(default=0, verbose_name='表示順'),
        ),
        migrations.AlterField(
            model_name='projectquestion',
            name='text',
            field=models.CharField(max_length=500, verbose_name='質問文'),
        ),
        migrations.RemoveField(
            model_name='projectanswer',
            name='ai_feedback',
        ),
    ]
